ML Stats Question 2:
    
    Generate 50 2-Dimensional feature vectors from a Gaussian distribution N(μ,S)
Where 
           μ = [ 2 , -2]   ,  S = [[0.9 , 0.2],
                                              [0.2 , 0.3]]

Let X be the resulting matrix having the features vector as columns. Compute the maximum likelihood(ML) estimate of mean value μ, and the covariance matrix, S, of  N(μ,S) and comment on the resulting estimates.


In [1]:
import numpy as np

In [10]:
mean = (2,-2)
cov = np.array([[0.9,0.2], [0.2, 0.3]])  # diagonal covariance

In [11]:
cov

array([[0.9, 0.2],
       [0.2, 0.3]])

In [12]:
X = np.random.multivariate_normal(mean, cov, 50)

In [13]:
N = X.shape[0]

# Estimate Gaussian parameters  and sigma_squared for every feature.
m = (1 / N) * np.sum(X, axis=0)
S = (1 / N) * np.sum((X - m) ** 2, axis=0)

In [14]:
m

array([ 2.092763  , -1.85504525])

In [15]:
# Gaussian parameters
S

array([0.80149191, 0.28512374])

The estimates are not exactly equivalent to the original values

For 5000 let's calculate

In [16]:
X = np.random.multivariate_normal(mean, cov, 5000)

In [17]:
N = X.shape[0]

# Estimate Gaussian parameters  and sigma_squared for every feature.
m = (1 / N) * np.sum(X, axis=0)
S = (1 / N) * np.sum((X - m) ** 2, axis=0)

In [18]:
m

array([ 2.0063655 , -1.98130611])

In [19]:
S

array([0.90202245, 0.29401193])